FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY MadridTransporte.Api/MadridTransporte.Api.csproj MadridTransporte.Api/
COPY MadridTransporte.Loader/MadridTransporte.Loader.csproj MadridTransporte.Loader/
RUN dotnet restore MadridTransporte.Loader/MadridTransporte.Loader.csproj
COPY MadridTransporte.Api/ MadridTransporte.Api/
COPY MadridTransporte.Loader/ MadridTransporte.Loader/
RUN dotnet publish MadridTransporte.Loader/MadridTransporte.Loader.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "MadridTransporte.Loader.dll"]
