FROM gradle:8.7.0-jdk21 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build -x test

FROM amazoncorretto:21.0.3
COPY . /build
RUN mkdir /app

COPY --from=build /home/gradle/src/loader/build/libs/loader.jar /app/loader.jar
ENTRYPOINT ["java", "-jar", "/app/loader.jar"]