FROM gradle:8.10.2-jdk21 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build -x test

FROM amazoncorretto:21.0.5
COPY . /build
RUN mkdir /app

COPY --from=build /home/gradle/src/api/build/libs/api.jar /app/api.jar
ENTRYPOINT ["java", "-jar", "/app/api.jar"]