
package crtm.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "MultimodalInformation", targetNamespace = "GEIS.MultimodalInfoWebService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MultimodalInformation {


    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.PublicKeyResponse
     */
    @WebMethod(operationName = "GetPublicKey", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetPublicKey")
    @WebResult(name = "PublicKeyResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public PublicKeyResponse getPublicKey(
        @WebParam(name = "PublicKeyRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        PublicKeyRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.BannerResponse
     */
    @WebMethod(operationName = "GetBanner", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetBanner")
    @WebResult(name = "BannerResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public BannerResponse getBanner(
        @WebParam(name = "BannerRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        BannerRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.TimeResponse
     */
    @WebMethod(operationName = "GetTime", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetTime")
    @WebResult(name = "TimeResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public TimeResponse getTime(
        @WebParam(name = "TimeRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        TimeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.LastDatesUpdateResponse
     */
    @WebMethod(operationName = "GetLastDatesUpdate", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetLastDatesUpdate")
    @WebResult(name = "LastDatesUpdateResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public LastDatesUpdateResponse getLastDatesUpdate(
        @WebParam(name = "LastDatesUpdateRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        LastDatesUpdateRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.ModeResponse
     */
    @WebMethod(operationName = "GetModes", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetModes")
    @WebResult(name = "ModeResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public ModeResponse getModes(
        @WebParam(name = "ModeRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        ModeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.LineResponse
     */
    @WebMethod(operationName = "GetLines", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetLines")
    @WebResult(name = "LineResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public LineResponse getLines(
        @WebParam(name = "LineRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        LineRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.LineItineraryResponse
     */
    @WebMethod(operationName = "GetLineItineraries", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetLineItineraries")
    @WebResult(name = "LineItineraryResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public LineItineraryResponse getLineItineraries(
        @WebParam(name = "LineItineraryRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        LineItineraryRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.StopResponse
     */
    @WebMethod(operationName = "GetStops", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetStops")
    @WebResult(name = "StopResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public StopResponse getStops(
        @WebParam(name = "StopRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        StopRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.StopResponse
     */
    @WebMethod(operationName = "GetStopsV2", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetStopsV2")
    @WebResult(name = "StopResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public StopResponse getStopsV2(
        @WebParam(name = "StopRequestV2", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        StopRequestV2 parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.StopGTFSResponse
     */
    @WebMethod(operationName = "GetStopsGTFS", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetStopsGTFS")
    @WebResult(name = "StopGTFSResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public StopGTFSResponse getStopsGTFS(
        @WebParam(name = "StopGTFSRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        StopGTFSRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.StopInformationResponse
     */
    @WebMethod(operationName = "GetStopsInformation", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetStopsInformation")
    @WebResult(name = "StopInformationResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public StopInformationResponse getStopsInformation(
        @WebParam(name = "StopInformationRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        StopInformationRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.MunicipalityResponse
     */
    @WebMethod(operationName = "GetMunicipalities", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetMunicipalities")
    @WebResult(name = "MunicipalityResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public MunicipalityResponse getMunicipalities(
        @WebParam(name = "MunicipalityRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        MunicipalityRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.CompanyResponse
     */
    @WebMethod(operationName = "GetCompanies", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetCompanies")
    @WebResult(name = "CompanyResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public CompanyResponse getCompanies(
        @WebParam(name = "CompanyRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        CompanyRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.LineInformationResponse
     */
    @WebMethod(operationName = "GetLinesInformation", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetLinesInformation")
    @WebResult(name = "LineInformationResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public LineInformationResponse getLinesInformation(
        @WebParam(name = "LineInformationRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        LineInformationRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.StopsByGeoLocationResponse
     */
    @WebMethod(operationName = "GetNearestStopsByGeoLocation", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetNearestStopsByGeoLocation")
    @WebResult(name = "StopsByGeoLocationResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public StopsByGeoLocationResponse getNearestStopsByGeoLocation(
        @WebParam(name = "StopsByGeoLocationRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        StopsByGeoLocationRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.LinesByStopResponse
     */
    @WebMethod(operationName = "GetLinesByStopCod", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetLinesByStopCod")
    @WebResult(name = "LinesByStopResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public LinesByStopResponse getLinesByStopCod(
        @WebParam(name = "LinesByStopRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        LinesByStopRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.OfficeResponse
     */
    @WebMethod(operationName = "GetOffices", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetOffices")
    @WebResult(name = "OfficeResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public OfficeResponse getOffices(
        @WebParam(name = "OfficeRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        OfficeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.OfficeResponse
     */
    @WebMethod(operationName = "GetOfficesV2", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetOfficesV2")
    @WebResult(name = "OfficeResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public OfficeResponse getOfficesV2(
        @WebParam(name = "OfficeRequestV2", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        OfficeRequestV2 parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.StopTimesResponse
     */
    @WebMethod(operationName = "GetStopTimes", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetStopTimes")
    @WebResult(name = "StopTimesResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public StopTimesResponse getStopTimes(
        @WebParam(name = "StopTimesRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        StopTimesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.ShortStopTimesResponse
     */
    @WebMethod(operationName = "GetShortStopTimes", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetShortStopTimes")
    @WebResult(name = "ShortStopTimesResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public ShortStopTimesResponse getShortStopTimes(
        @WebParam(name = "ShortStopTimesRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        ShortStopTimesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.StopTimesDateResponse
     */
    @WebMethod(operationName = "GetStopTimesByDate", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetStopTimesByDate")
    @WebResult(name = "StopTimesDateResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public StopTimesDateResponse getStopTimesByDate(
        @WebParam(name = "StopTimesDateRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        StopTimesDateRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.LineLocationResponse
     */
    @WebMethod(operationName = "GetLineLocation", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetLineLocation")
    @WebResult(name = "LineLocationResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public LineLocationResponse getLineLocation(
        @WebParam(name = "LineLocationRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        LineLocationRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.IncidentsAffectationsResponse
     */
    @WebMethod(operationName = "GetIncidentsAffectations", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetIncidentsAffectations")
    @WebResult(name = "IncidentsAffectationsResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public IncidentsAffectationsResponse getIncidentsAffectations(
        @WebParam(name = "IncidentsAffectationsRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        IncidentsAffectationsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.LinesTimePlanningResponse
     */
    @WebMethod(operationName = "GetLinesTimePlanning", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetLinesTimePlanning")
    @WebResult(name = "LinesTimePlanningResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public LinesTimePlanningResponse getLinesTimePlanning(
        @WebParam(name = "LinesTimePlanningRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        LinesTimePlanningRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.TimePlanningResponse
     */
    @WebMethod(operationName = "GetTimePlanning", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetTimePlanning")
    @WebResult(name = "TimePlanningResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public TimePlanningResponse getTimePlanning(
        @WebParam(name = "TimePlanningRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        TimePlanningRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.PlatformsResponse
     */
    @WebMethod(operationName = "GetPlatforms", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetPlatforms")
    @WebResult(name = "PlatformsResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public PlatformsResponse getPlatforms(
        @WebParam(name = "PlatformsRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        PlatformsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.LinesByPlatformResponse
     */
    @WebMethod(operationName = "GetLinesByPlatform", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetLinesByPlatform")
    @WebResult(name = "LinesByPlatformResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public LinesByPlatformResponse getLinesByPlatform(
        @WebParam(name = "LinesByPlatformRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        LinesByPlatformRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.SponsorResponse
     */
    @WebMethod(operationName = "GetSponsors", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetSponsors")
    @WebResult(name = "SponsorResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public SponsorResponse getSponsors(
        @WebParam(name = "SponsorRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        SponsorRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.PoiResponse
     */
    @WebMethod(operationName = "GetPois", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetPois")
    @WebResult(name = "PoiResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public PoiResponse getPois(
        @WebParam(name = "PoiRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        PoiRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.EstimationsResponse
     */
    @WebMethod(operationName = "GetEstimations", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetEstimations")
    @WebResult(name = "EstimationsResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public EstimationsResponse getEstimations(
        @WebParam(name = "EstimationsRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        EstimationsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.AppsKMLsResponse
     */
    @WebMethod(operationName = "GetAppsKMLs", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetAppsKMLs")
    @WebResult(name = "AppsKMLsResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public AppsKMLsResponse getAppsKMLs(
        @WebParam(name = "AppsKMLsRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        AppsKMLsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.CalendarsResponse
     */
    @WebMethod(operationName = "GetCalendars", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetCalendars")
    @WebResult(name = "CalendarsResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public CalendarsResponse getCalendars(
        @WebParam(name = "CalendarsRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        CalendarsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.TripsResponse
     */
    @WebMethod(operationName = "GetTrips", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetTrips")
    @WebResult(name = "TripsResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public TripsResponse getTrips(
        @WebParam(name = "TripsRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        TripsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.FrequencyTripsResponse
     */
    @WebMethod(operationName = "GetFrequencyTrips", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/GetFrequencyTrips")
    @WebResult(name = "FrequencyTripsResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public FrequencyTripsResponse getFrequencyTrips(
        @WebParam(name = "FrequencyTripsRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        FrequencyTripsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.TripUpdatesResponse
     */
    @WebMethod(operationName = "CheckTripUpdates", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/CheckTripUpdates")
    @WebResult(name = "TripUpdatesResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public TripUpdatesResponse checkTripUpdates(
        @WebParam(name = "TripUpdatesRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        TripUpdatesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns crtm.soap.AlertsResponse
     */
    @WebMethod(operationName = "CheckAlerts", action = "GEIS.MultimodalInfoWebService/MultimodalInformation/CheckAlerts")
    @WebResult(name = "AlertsResponse", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
    public AlertsResponse checkAlerts(
        @WebParam(name = "AlertsRequest", targetNamespace = "GEIS.MultimodalInfoWebService", partName = "parameters")
        AlertsRequest parameters);

}
