
package crtm.abono;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IVentaPrepagoTitulo", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVentaPrepagoTitulo {


    /**
     * 
     * @param sNumeroTTP
     * @return
     *     returns crtm.abono.RespuestaVentaPrepagoTituloConsultaSaldo1
     */
    @WebMethod(operationName = "ConsultaSaldo1", action = "http://tempuri.org/IVentaPrepagoTitulo/ConsultaSaldo1")
    @WebResult(name = "ConsultaSaldo1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaSaldo1", targetNamespace = "http://tempuri.org/", className = "crtm.abono.ConsultaSaldo1")
    @ResponseWrapper(localName = "ConsultaSaldo1Response", targetNamespace = "http://tempuri.org/", className = "crtm.abono.ConsultaSaldo1Response")
    public RespuestaVentaPrepagoTituloConsultaSaldo1 consultaSaldo1(
        @WebParam(name = "sNumeroTTP", targetNamespace = "http://tempuri.org/")
        String sNumeroTTP);

    /**
     * 
     * @param sLenguaje
     * @param sNumeroTP
     * @param sTipoApp
     * @return
     *     returns crtm.abono.RespuestaInformacionTarjetaConsultaSaldo1
     */
    @WebMethod(operationName = "ConsultaSaldoTarjeta1", action = "http://tempuri.org/IVentaPrepagoTitulo/ConsultaSaldoTarjeta1")
    @WebResult(name = "ConsultaSaldoTarjeta1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaSaldoTarjeta1", targetNamespace = "http://tempuri.org/", className = "crtm.abono.ConsultaSaldoTarjeta1")
    @ResponseWrapper(localName = "ConsultaSaldoTarjeta1Response", targetNamespace = "http://tempuri.org/", className = "crtm.abono.ConsultaSaldoTarjeta1Response")
    public RespuestaInformacionTarjetaConsultaSaldo1 consultaSaldoTarjeta1(
        @WebParam(name = "sNumeroTP", targetNamespace = "http://tempuri.org/")
        String sNumeroTP,
        @WebParam(name = "sLenguaje", targetNamespace = "http://tempuri.org/")
        String sLenguaje,
        @WebParam(name = "sTipoApp", targetNamespace = "http://tempuri.org/")
        String sTipoApp);

}
