name: Publish Docker image And Deploy

on:
  push:
    tags: [ "*" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for api
        id: meta_api
        uses: docker/metadata-action@115662203e5f4c9b240a57397f721baaab82a488
        with:
          images: xbank/bus_tracker_api

      - name: Build and push Docker image for api
        uses: docker/build-push-action@5e99dacf67635c4f273e532b9266ddb609b3025a
        with:
          context: .
          file: Dockerfile-api
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}
          name: remote ssh command

      - name: Extract metadata (tags, labels) for loader
        id: meta_loader
        uses: docker/metadata-action@115662203e5f4c9b240a57397f721baaab82a488
        with:
          images: xbank/bus_tracker_loader

      - name: Build and push Docker image for loader
        uses: docker/build-push-action@5e99dacf67635c4f273e532b9266ddb609b3025a
        with:
          context: .
          file: Dockerfile-loader
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta_loader.outputs.tags }}
          labels: ${{ steps.meta_loader.outputs.labels }}
          name: remote ssh command
