name: Publish Docker image And Deploy

on:
  push:
    tags: [ "*" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@d910b140723c904c9e74efef5dc6af05d5143104
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@2ee3d3070bb41b40bf7305d15233321e12c1dc5c
        with:
          images: xbank/bus_tracker_api

      - name: Build and push Docker image
        uses: docker/build-push-action@729f7f49266dec5e72fe7339273d3f7e65abacd7
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          name: remote ssh command
