name: Publish Docker image And Deploy

on:
  push:
    tags: [ "*" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@406e1d71198d2324043d77a06783c53195decb37
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@839b70f9d59b3fa5a8b9f64a9e4f532e5df8a047
        with:
          images: xbank/bus_tracker_api

      - name: Build and push Docker image
        uses: docker/build-push-action@df19a799eba09c72273c5a94c70800e243e76ebc
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          name: remote ssh command
